name: esip
channels:
  - defaults
dependencies:
  - cartopy
  - pip:
    - panel
    - duckdb
    - fastparquet
    - pandas
    - geoviews
    - holoviews
    - statsmodels
    - scikit-learn
    - hvplot
prefix: /Users/ahuang/miniconda3/envs/esip
